name: pla-enrichment
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base=4.3.3
  - r-essentials
  - r-seurat=5.0.3
  - r-tidyverse
  - r-soupx
  - r-clustree
  - bioconductor-scdblfinder
  - bioconductor-singlecellexperiment
  - bioconductor-scater
  - bioconductor-scran
  - bioconductor-scuttle

